name: CI - Build and Push to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Vote Image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t 982081078488.dkr.ecr.us-east-1.amazonaws.com/vote:$IMAGE_TAG ./vote
          docker push 982081078488.dkr.ecr.us-east-1.amazonaws.com/vote:$IMAGE_TAG

      - name: Build, Tag, and Push Result Image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t 982081078488.dkr.ecr.us-east-1.amazonaws.com/result:$IMAGE_TAG ./result
          docker push 982081078488.dkr.ecr.us-east-1.amazonaws.com/result:$IMAGE_TAG

      - name: Build, Tag, and Push Worker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t 982081078488.dkr.ecr.us-east-1.amazonaws.com/worker:$IMAGE_TAG ./worker
          docker push 982081078488.dkr.ecr.us-east-1.amazonaws.com/worker:$IMAGE_TAG
